#!/usr/bin/env ruby

require_relative '../lib/huawei_cli'

opt = ARGV.shift

cnx = HuaweiCli::Connection.new('https://10.0.0.42')

case opt
when 'ping'
  HuaweiCli::Cmd::Ping.new(cnx).run
when 'signal'
  HuaweiCli::Cmd::Signal.new(cnx).run
else
  puts "Unknown command: #{opt}"
end

cnx.close
