#!/usr/bin/env ruby

require 'dotenv'

require_relative '../lib/huawei_cli'

Dotenv.load

def fetch_cmd(cnx, opts)
  opt = ARGV.shift

  ret = case opt
  when 'ping'
    HuaweiCli::Cmd::Ping.new(cnx, ARGV)
  when 'signal'
    HuaweiCli::Cmd::Signal.new(cnx, ARGV)
  when 'loop'
    HuaweiCli::Cmd::Loop.new(cnx, ARGV)
  else
    puts "Unknown command: #{opt}"
  end
  ret
end

cnx = HuaweiCli::Connection.new(ENV['HC_ROUTER'])
fetch_cmd(cnx, ARGV).run
cnx.close
